### ISSUE TITLE
parsing item in variable to text

### ISSUE THREAD

**Issue by Edgarsz-zz** [Mirreski/Skript#17]
command /test:
    trigger:
        set {_item} to player's tool
        set {_itemtext} to {_item} parsed as text
        send "%{_itemtext}%"

Output:
<code><,none></code>

This is big problem becouse i want to remove amount of this item from variable.

**Comment by Mirreski** [comment]
I don't think you really understood how parse work. Since it's supposed to parse a text into something else. Not parsing a item into a text when you can just do message "%{_item}%" to turn it into text..

I am actually not 100% sure what you want. Remove the amount from the text?

Try(works for me)

```
set {_item} to "%tool of player%"
set {_parsed::*} to {_item} parsed as "%number% %text%"
if size of {_parsed::*} is 2:
    set {_itemtext} to {_parsed::2}
else if size of {_parsed::*} is 0:
    set {_itemtext} to {_item}
message "Item: %{_itemtext}%"   
```

**Comment by Mirreski** [comment]
Closing since this is not a bug and just an incorrect usage.
