### ISSUE TITLE
on walking on block bugging

### ISSUE THREAD

**Issue by xNorbig** [Mirreski/Skript#23]
if i use code:

on walking on bedrock:
    if {variable::%location of event-block%} is set:
        send "You are walking on bedrock! O.O"

then, Skript "teleporting" me to this block. (block is setting on 1 tick to "ghost" and setting to solid block)

Sorry for bad english.

**Comment by Mirreski** [comment]
Yeah I don't understand what you mean.

**Comment by Pilvinen** [comment]
I think what he means is that if you try to use the "on walking on" event to do something that takes time to do - the player will bug out and teleport/fall through the event-material that he is walking on.

But I'm not sure if you could call it a bug. The "on walking on" event is just so intensive that the only correct way to handle such situations would be to run the things you want to run after the event has happened - either by setting a small delay ie. "wait for 0.0000001 ticks" or some such or by using a command to run the code that you want to run.

Just guessing though, his English really was rather bad.
