### ISSUE TITLE
Integer variables not being compared properly.

### ISSUE THREAD

**Issue by Gamebuster19901** [Mirreski/Skript#25]
This code isn't reading/comparing the variable {pingTimer.%player%} and 0 correctly.

The code can be found here: http://pastebin.com/raw.php?i=wGFiM9bU

The full debug message can be found here: http://pastebin.com/raw.php?i=viaWH1ay

**Comment by Gamebuster19901** [comment]
Note that this did work in version 6.

**Comment by Mirreski** [comment]
Actually works fine for me. Server doesn't hang or anything.

The line "subtract 1 from {pingTimer.%player}"  is missing a "%" at the "%player}". Might be the problem?

**Comment by Mirreski** [comment]
Was a mistake.
