### ISSUE TITLE
Connection with SQLite [V8]

### ISSUE THREAD

**Issue by Sopher** [Mirreski/Skript#27]
I found next problem about variables in databases. When I try run server if I set database "SQLite" in skript config and I get error: http://pastebin.com/raw.php?i=x0Shf66j

**Comment by Sopher** [comment]
Ahh, Skript still using old version of SQLibrary. Here you will change it: http://prntscr.com/7lyxna for new version, 7.1 So if you can change it asap i will be grateful :)

**Comment by Mirreski** [comment]
Okay could you try with this version? It's the Skript 2.2 Fixes V7 version with an addition and compiled with SqlLibrary 7.1. I mean even if it's outdated, updating might not fix the problem.

https://www.dropbox.com/s/rwwa2yg3ix1v5eo/skript.jar?dl=0

**Comment by Sopher** [comment]
It's still don't work. New error: http://pastebin.com/raw.php?i=rSLLjs40
If it will be helpful for you I using spigot 1.8 from http://getspigot.org/

**Comment by Mirreski** [comment]
It's the same error. And the spigot version doesn't matter so much but indeed I am already using a version from there.

Actually if you pre-define a table named "variables21", that error will not come up. (I haven't tested but that's basicly what it says, it's missing a table named "variables21" and that's were variables are gonna get put).

As I said in the other issue you made, I am no expert at MySQL/SQlite database stuff. I have never setup a database for Skript as I have always stayed on flatfile. So I am not confident on fixing database related problems.

**Comment by Sopher** [comment]
I made default database with this instructions: https://github.com/Mirreski/Skript/blob/master/src/main/java/ch/njol/skript/variables/DatabaseStorage.java
Default database SQLite file you can check here: http://skript.pl/_sopher/_skript/default_sqlite.db
It's working now, but I think you will fix it :p 
My sample database file: http://screenshooter.net/102182620/lrpnvqk

**Comment by Mirreski** [comment]
Thanks to Pirat for fixing this!
