### ISSUE TITLE
Redstone event cannot be cancelled

### ISSUE THREAD

**Issue by Pilvinen** [Mirreski/Skript#32]
Currently the "on redstone" event cannot be cancelled. It would be useful if it could be cancelled. It's not a bug per say, but since you can cancel redstone events in "on physics" event (which has it's own problems - separating block breaking from power events, etc) this could be seen as a "bug".

It would probably be a very simple thing to fix afaik. I've no idea why it wasn't implemented in the first place.

I know the "on redstone" event isn't probably very popular because of it's lack of other features but nonetheless I find it very useful and being able to cancel the events would make it even more useful.

**Comment by Mirreski** [comment]
I looked it up and the "on redstone"(BlockRedstoneEvent) event in Bukkit/Spigot is not cancellable. If it was cancellable, Skript would automaticly make the skript event cancellable and "cancel event" could be called inside the event.

So I can't do anything about it:/
