### ISSUE TITLE
Skript doesn't know the new entities by name

### ISSUE THREAD

**Issue by Pilvinen** [Mirreski/Skript#35]
Support for rabbits and armor stands is missing. I can't recall if there were any other new entities.

**Comment by Mirreski** [comment]
I added those early on when I started with this:) https://github.com/Mirreski/Skript/issues/6

**Comment by Pilvinen** [comment]
Oh. Ok. I checked the tickets but I didn't recognize it from the topic. Good job :-)

**Comment by Mirreski** [comment]
Yea I used "EntityData" in the topic which most people don't understand what it refers to:P

Changing topic name of that one:)
