### ISSUE TITLE
number of all chickens

### ISSUE THREAD

**Issue by heliomcp** [Mirreski/Skript#37]
Works fine:
`message "counted %number of all cows% Cows in the world"`
`add number of all cows to {_allCreatures}`

Doesnt work:
`message "counted %number of all chickens% Chickens in the world"`
`add number of all chickens to {_allCreatures}`

Error:
`Can't loop chicken item or cooked chicken because it's only a single value (chicken.sk, line 7: loop chickens:')`

**Comment by Mirreski** [comment]
Strange error. Honestly no idea what could be causing it.

But this works apparantly.

```
set {_allCreatures::*} to all chickens
message "counted %amount of {_allCreatures::*}% Chickens in the world"
```

Need to test to see if this issue has been in Skript 2.2 and/or Skript 2.1.2.
